services:
  db:
    image: bitnami/mongodb:5.0.17
    ports:
      - 27017:27017
    environment:
      MONGODB_ROOT_PASSWORD: root
      MONGODB_USERNAME: primary
      MONGODB_PASSWORD: 123456
      MONGODB_DATABASE: bolsa_valores
